#!/usr/bin/python
# -*- coding: UTF-8 -*-

QINIU_ACCESS_KEY = "qZUvN3pdML7x0pa4LPoP2iLI5iif0DP1l5JLx1Ax"
QINIU_SECRET_KEY = "oPFZOqG6dV2cuX1krZsLT1vkDBVeEzaUKYZYuQsc"
QINIU_DN_DOMAIN = "kuangnei.qiniudn.com"
QINIU_SCOP = "kuangnei"

LOAD_SIZE = 5
FIRST_LEVEL_REPLY_LOAD_SIZE = 10
SECOND_LEVEL_REPLY_LOAD_SIZE = 5
