#!/usr/bin/python
# -*- coding: UTF-8 -*-

QINIU_ACCESS_KEY = "qZUvN3pdML7x0pa4LPoP2iLI5iif0DP1l5JLx1Ax"
QINIU_SECRET_KEY = "oPFZOqG6dV2cuX1krZsLT1vkDBVeEzaUKYZYuQsc"
QINIU_DN_DOMAIN = "kuangnei.qiniudn.com"
QINIU_SCOP = "kuangnei"

POST_LOAD_SIZE = 7
REPLY_LOAD_SIZE = 15
REPLY_INFO_LOAD_SIZE = 15

REPLY_POST = 1
REPLY_FIRST_LEVEL = 2
REPLY_SECOND_LEVEL = 3

# seconds since epoch to 2014.9.8 11:07
BASE_TIME = 1410145675
SIX_HOUR_SECONDS = 21600.0
FORBIDDEN_THRESHOLD = 15
FORBIDDEN_AUTH = 'forbidden'

# 最新帖子channelId
NEWEST_CHANNEL_ID = 100

# 热门帖子channelId
HOTTEST_CHANNEL_ID = 101

#次数限制
FLOATER_COUNT_LIMIT = 3  #漂流瓶的次数限制
POST_COUNT_LIMIT = 3  #发帖次数限制
